# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/Dreamacro/clash"
  revision = "f69f635e0b0ada91f68be3a8566cf36e51f81818"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[override]]
  name = "github.com/eycorsican/go-tun2socks"
  source = "github.com/trojan-gfw/go-tun2socks"
  revision = "efeee82202ff1e4664bec98fd08a413f703a9f9a"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/eycorsican/go-tun2socks"
    non-go = false
    unused-packages = false
