# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/Dreamacro/clash"
  version = "0.17.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[override]]
  branch = "master"
  name = "github.com/eycorsican/go-tun2socks"
  source = "github.com/trojan-gfw/go-tun2socks"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/eycorsican/go-tun2socks"
    non-go = false
    unused-packages = false
